/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'marialaura' at '3/14/17 12:41 PM' with Gradle 2.14.1
 *
 * @author marialaura, @date 3/14/17 12:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
